import { Project } from "./types";

export const initialProjects: Project[] = [
  {
    id: "proj-1",
    title: "NOIR ÉTERNEL // Haute Couture 2026",
    client: "Maison Saint Laurent",
    category: "Cinematography",
    description: "An anamorphic 35mm global visual campaign exploring the boundary between shadow, crimson silhouettes, and haute couture tailoring. Shot across nocturnal Paris and Milan.",
    coverImage: "https://images.unsplash.com/photo-1509631179647-0177331693ae?auto=format&fit=crop&w=1600&q=85",
    videoUrl: "https://assets.mixkit.co/videos/preview/mixkit-set-of-plateaus-seen-from-the-sky-in-a-sunset-26070-large.mp4",
    aspectRatio: "cinematic",
    tags: ["Anamorphic 35mm", "Directing", "Color Grade", "VFX"],
    year: "2026",
    featured: true,
    awards: ["Cannes Lions Gold 2026", "D&AD Graphite Pencil"],
    cameraSpecs: "ARRI Alexa 35 + Cooke Anamorphic /i Full Frame Plus",
    deliverables: ["60s Hero Film", "3x 15s Global Cutdowns", "Key Visual Stills", "Billboard 3D Loop"],
    metrics: "+4.2M Organic Views across digital rollout",
    createdAt: "2026-02-15T12:00:00.000Z"
  },
  {
    id: "proj-2",
    title: "AERODYNAMICS OF SPEED // SF90 Hypercar",
    client: "Scuderia Maranello / Private Client",
    category: "Premium Photography",
    description: "High-speed light-painting and precision studio captures for an ultra-rare carbon-chassis hypercar in an anti-reflective subterranean bunker.",
    coverImage: "https://images.unsplash.com/photo-1617788138017-80ad40651399?auto=format&fit=crop&w=1400&q=85",
    aspectRatio: "landscape",
    tags: ["Hypercar", "Studio Lighting", "High Speed Sync", "Carbon Finish"],
    year: "2026",
    featured: true,
    awards: ["International Photography Awards - 1st Place Advertising"],
    cameraSpecs: "Hasselblad H6D-100c + HC 2,2/100mm",
    deliverables: ["12 Monograph Stills", "Collector Coffee Table Book", "Digital Configurator Assets"],
    metrics: "Featured in TopGear & Robb Report",
    createdAt: "2026-01-20T10:30:00.000Z"
  },
  {
    id: "proj-3",
    title: "ROYAL CHRONOGRAPH // The Crimson Tourbillon",
    client: "Audemars & Cie Fine Horology",
    category: "Graphic Design",
    description: "Complete visual identity, 3D kinetic typography, and digital art direction for a limited 50-piece bespoke tourbillon timepiece.",
    coverImage: "https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?auto=format&fit=crop&w=1200&q=85",
    aspectRatio: "portrait",
    tags: ["3D Typography", "Fine Horology", "Brand Architecture", "Custom Typeface"],
    year: "2025",
    featured: true,
    awards: ["Tokyo TDC Annual Book", "Awwwards Site of the Day"],
    cameraSpecs: "Houdini 3D Engine + Octane Render 4K HDR",
    deliverables: ["Custom Serif Variable Font", "3D Kinetic Hologram", "Packaging Box Architecture"],
    metrics: "Edition sold out in 4 minutes",
    createdAt: "2025-11-10T14:00:00.000Z"
  },
  {
    id: "proj-4",
    title: "L'ORCHIDÉE ROUGE // Villa d'Este Luxury Nuptials",
    client: "Private Monaco Family",
    category: "Premium Photography",
    description: "Editorial documentary photography for a 3-day multi-million dollar royal celebration on the shores of Lake Como.",
    coverImage: "https://images.unsplash.com/photo-1519741497674-611481863552?auto=format&fit=crop&w=1400&q=85",
    aspectRatio: "portrait",
    tags: ["Royal Nuptials", "Editorial Portraiture", "Medium Format", "Lake Como"],
    year: "2025",
    featured: true,
    awards: ["Vogue Weddings Featured Story", "Brides International Best Visual 2025"],
    cameraSpecs: "Leica SL3 + Summilux-SL 50mm f/1.4 ASPH",
    deliverables: ["400 Master Color Grades", "Custom Leather Embossed Album", "Cinematic Teaser Stills"],
    metrics: "Private Archive with 100% Confidentiality Protocol",
    createdAt: "2025-09-05T08:00:00.000Z"
  },
  {
    id: "proj-5",
    title: "MONOLITH // Architectural Biennale Pavilion",
    client: "Fondazione Biennale di Venezia",
    category: "Art Direction",
    description: "Curatorial identity and spatial motion graphics for an immersive installation celebrating dark matter and brutalist structural design.",
    coverImage: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1400&q=85",
    aspectRatio: "landscape",
    tags: ["Spatial Experience", "Brutalist Design", "Spatial Sound", "Interactive Lighting"],
    year: "2025",
    featured: false,
    awards: ["Venice Golden Lion Candidate"],
    cameraSpecs: "RED V-Raptor 8K VV + Zeiss Supreme Primes",
    deliverables: ["Interactive Spatial Projections", "Catalog Design", "Curatorial Documentaries"],
    metrics: "280,000 Visitors over 6-month exhibition",
    createdAt: "2025-07-12T16:20:00.000Z"
  },
  {
    id: "proj-6",
    title: "VALKYRIE // Apex Formula Campaign",
    client: "Aston Martin Racing & Red Bull",
    category: "Cinematography",
    description: "High-octane commercial film shot at Circuit Paul Ricard with high-g tracking gyro systems and night atmospheric mist.",
    coverImage: "https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=1400&q=85",
    videoUrl: "https://assets.mixkit.co/videos/preview/mixkit-traffic-lights-at-night-in-a-city-43224-large.mp4",
    aspectRatio: "cinematic",
    tags: ["High Velocity", "Motorsport", "Gyro Chase Cam", "Sound Design"],
    year: "2025",
    featured: true,
    awards: ["Clio Awards Silver 2025"],
    cameraSpecs: "Sony Venice 2 8K + Rialto 2 Gyro-Stabilized System",
    deliverables: ["90s Director's Cut", "TV Broadcast Master", "Soundtrack Master (Dolby Atmos)"],
    metrics: "Over 12M global broadcast impressions",
    createdAt: "2025-05-18T18:00:00.000Z"
  },
  {
    id: "proj-7",
    title: "AURA // High Jewelry Diamond Nocturne",
    client: "Cartier High Jewellery & Art",
    category: "Graphic Design",
    description: "Bespoke digital catalog design, microsite typography, and micro-macro diamond light dispersion renders.",
    coverImage: "https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?auto=format&fit=crop&w=1200&q=85",
    aspectRatio: "square",
    tags: ["High Jewelry", "Micro Macro", "Luxury Packaging", "Editorial Layout"],
    year: "2025",
    featured: false,
    awards: ["Red Dot Design: Best of the Best 2025"],
    cameraSpecs: "Phase One IQ4 150MP Achromatic",
    deliverables: ["Bespoke Digital Gallery", "VIP Private Viewing App", "Print Silk-Screened Lookbook"],
    metrics: "Direct engagement for 150 private billionaire collectors",
    createdAt: "2025-04-02T11:45:00.000Z"
  },
  {
    id: "proj-8",
    title: "SOLITUDE // Arctic Soundscape & Film",
    client: "National Geographic Creative Expeditions",
    category: "Cinematography",
    description: "Cinematic drone odyssey and 8K documentary capturing the frozen majesty of Svalbard during the midnight sun transition.",
    coverImage: "https://images.unsplash.com/photo-1517411032315-54ef2cb783bb?auto=format&fit=crop&w=1400&q=85",
    videoUrl: "https://assets.mixkit.co/videos/preview/mixkit-set-of-plateaus-seen-from-the-sky-in-a-sunset-26070-large.mp4",
    aspectRatio: "portrait",
    tags: ["Extreme Expedition", "Aerial Cinema", "Ambient Soundtrack", "Conservation"],
    year: "2025",
    featured: false,
    awards: ["Tribeca X Official Selection"],
    cameraSpecs: "Inspire 3 8K CinemaDNG + Zenmuse X9-8K Air",
    deliverables: ["Short Film (12min)", "Photo Essay in NatGeo", "Soundtrack Album on Vinyl"],
    metrics: "Winner of Grand Jury Prize at Mountain Film Fest",
    createdAt: "2025-02-14T09:10:00.000Z"
  }
];

export const initialLeads = [
  {
    id: "lead-101",
    name: "Lord Julian Sterling",
    email: "sterling@sterling-heritage.ch",
    company: "Sterling Heritage Fine Watches (Geneva)",
    service: "Cinematography & Brand Campaign",
    budgetBracket: "$75k - $150k",
    timeline: "Q4 2026 (November)",
    location: "Geneva & St. Moritz",
    projectScale: "Multi-country Cinema Production with Drone & Cinema Crew",
    notes: "We require a cinematic film for the global unveiling of our 150th anniversary grand complication piece. Exclusive confidentiality required.",
    status: "Qualified" as const,
    leadScore: 98,
    createdAt: "2026-09-28T14:22:00.000Z"
  },
  {
    id: "lead-102",
    name: "Elena Rostova",
    email: "e.rostova@atelier-nocturne.fr",
    company: "Atelier Nocturne Haute Couture (Paris)",
    service: "Art Direction & 3D Typography",
    budgetBracket: "$30k - $75k",
    timeline: "January 2027",
    location: "Paris, Place Vendôme",
    projectScale: "Complete Runway Visual System & Digital Art Direction",
    notes: "Looking for dark crimson aesthetic with antigravity particle floating typography.",
    status: "In Discussion" as const,
    leadScore: 92,
    createdAt: "2026-09-29T18:40:00.000Z"
  }
];
